#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MyAndroid.Resource", IsApplication=true)]

namespace MyAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050006
			public const int BinderButton = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int GetTimestamperbutton = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int UNBinderButton = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int messageText = 2131034119;
			
			// aapt resource value: 0x7f050003
			public const int sendButton = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int test_notifications = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int test_service = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int textView1 = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int TestNotification = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int TestService = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040007
			public const int binder = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int binder_service = 2130968584;
			
			// aapt resource value: 0x7f04000b
			public const int get_timestamper_service = 2130968587;
			
			// aapt resource value: 0x7f040001
			public const int hello_world = 2130968577;
			
			// aapt resource value: 0x7f040005
			public const int satrt = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int send = 2130968580;
			
			// aapt resource value: 0x7f04000c
			public const int service_not_connected = 2130968588;
			
			// aapt resource value: 0x7f040006
			public const int stop = 2130968582;
			
			// aapt resource value: 0x7f040002
			public const int test_notifications = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int test_service = 2130968579;
			
			// aapt resource value: 0x7f040009
			public const int un_binder = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int un_binder_service = 2130968586;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
